// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nodo_procesamiento.proto

// Protobuf Java Version: 3.25.3
package co.edu.upb.grpc;

/**
 * Protobuf type {@code nodoprocesamiento.EstadoNodoResponse}
 */
public final class EstadoNodoResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:nodoprocesamiento.EstadoNodoResponse)
    EstadoNodoResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use EstadoNodoResponse.newBuilder() to construct.
  private EstadoNodoResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private EstadoNodoResponse() {
    idNodo_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new EstadoNodoResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return co.edu.upb.grpc.NodoProcesamientoProto.internal_static_nodoprocesamiento_EstadoNodoResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return co.edu.upb.grpc.NodoProcesamientoProto.internal_static_nodoprocesamiento_EstadoNodoResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            co.edu.upb.grpc.EstadoNodoResponse.class, co.edu.upb.grpc.EstadoNodoResponse.Builder.class);
  }

  public static final int IDNODO_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object idNodo_ = "";
  /**
   * <code>string idNodo = 1;</code>
   * @return The idNodo.
   */
  @java.lang.Override
  public java.lang.String getIdNodo() {
    java.lang.Object ref = idNodo_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      idNodo_ = s;
      return s;
    }
  }
  /**
   * <code>string idNodo = 1;</code>
   * @return The bytes for idNodo.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdNodoBytes() {
    java.lang.Object ref = idNodo_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      idNodo_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ACTIVO_FIELD_NUMBER = 2;
  private boolean activo_ = false;
  /**
   * <code>bool activo = 2;</code>
   * @return The activo.
   */
  @java.lang.Override
  public boolean getActivo() {
    return activo_;
  }

  public static final int CAPACIDADMAXIMA_FIELD_NUMBER = 3;
  private int capacidadMaxima_ = 0;
  /**
   * <code>int32 capacidadMaxima = 3;</code>
   * @return The capacidadMaxima.
   */
  @java.lang.Override
  public int getCapacidadMaxima() {
    return capacidadMaxima_;
  }

  public static final int CARGAACTUAL_FIELD_NUMBER = 4;
  private int cargaActual_ = 0;
  /**
   * <code>int32 cargaActual = 4;</code>
   * @return The cargaActual.
   */
  @java.lang.Override
  public int getCargaActual() {
    return cargaActual_;
  }

  public static final int CAPACIDADDISPONIBLE_FIELD_NUMBER = 5;
  private int capacidadDisponible_ = 0;
  /**
   * <code>int32 capacidadDisponible = 5;</code>
   * @return The capacidadDisponible.
   */
  @java.lang.Override
  public int getCapacidadDisponible() {
    return capacidadDisponible_;
  }

  public static final int HILOSCONFIGURADOS_FIELD_NUMBER = 6;
  private int hilosConfigurados_ = 0;
  /**
   * <code>int32 hilosConfigurados = 6;</code>
   * @return The hilosConfigurados.
   */
  @java.lang.Override
  public int getHilosConfigurados() {
    return hilosConfigurados_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(idNodo_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, idNodo_);
    }
    if (activo_ != false) {
      output.writeBool(2, activo_);
    }
    if (capacidadMaxima_ != 0) {
      output.writeInt32(3, capacidadMaxima_);
    }
    if (cargaActual_ != 0) {
      output.writeInt32(4, cargaActual_);
    }
    if (capacidadDisponible_ != 0) {
      output.writeInt32(5, capacidadDisponible_);
    }
    if (hilosConfigurados_ != 0) {
      output.writeInt32(6, hilosConfigurados_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(idNodo_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, idNodo_);
    }
    if (activo_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, activo_);
    }
    if (capacidadMaxima_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, capacidadMaxima_);
    }
    if (cargaActual_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, cargaActual_);
    }
    if (capacidadDisponible_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, capacidadDisponible_);
    }
    if (hilosConfigurados_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, hilosConfigurados_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof co.edu.upb.grpc.EstadoNodoResponse)) {
      return super.equals(obj);
    }
    co.edu.upb.grpc.EstadoNodoResponse other = (co.edu.upb.grpc.EstadoNodoResponse) obj;

    if (!getIdNodo()
        .equals(other.getIdNodo())) return false;
    if (getActivo()
        != other.getActivo()) return false;
    if (getCapacidadMaxima()
        != other.getCapacidadMaxima()) return false;
    if (getCargaActual()
        != other.getCargaActual()) return false;
    if (getCapacidadDisponible()
        != other.getCapacidadDisponible()) return false;
    if (getHilosConfigurados()
        != other.getHilosConfigurados()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + IDNODO_FIELD_NUMBER;
    hash = (53 * hash) + getIdNodo().hashCode();
    hash = (37 * hash) + ACTIVO_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getActivo());
    hash = (37 * hash) + CAPACIDADMAXIMA_FIELD_NUMBER;
    hash = (53 * hash) + getCapacidadMaxima();
    hash = (37 * hash) + CARGAACTUAL_FIELD_NUMBER;
    hash = (53 * hash) + getCargaActual();
    hash = (37 * hash) + CAPACIDADDISPONIBLE_FIELD_NUMBER;
    hash = (53 * hash) + getCapacidadDisponible();
    hash = (37 * hash) + HILOSCONFIGURADOS_FIELD_NUMBER;
    hash = (53 * hash) + getHilosConfigurados();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static co.edu.upb.grpc.EstadoNodoResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static co.edu.upb.grpc.EstadoNodoResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static co.edu.upb.grpc.EstadoNodoResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static co.edu.upb.grpc.EstadoNodoResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static co.edu.upb.grpc.EstadoNodoResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static co.edu.upb.grpc.EstadoNodoResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static co.edu.upb.grpc.EstadoNodoResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static co.edu.upb.grpc.EstadoNodoResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static co.edu.upb.grpc.EstadoNodoResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static co.edu.upb.grpc.EstadoNodoResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static co.edu.upb.grpc.EstadoNodoResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static co.edu.upb.grpc.EstadoNodoResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(co.edu.upb.grpc.EstadoNodoResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code nodoprocesamiento.EstadoNodoResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:nodoprocesamiento.EstadoNodoResponse)
      co.edu.upb.grpc.EstadoNodoResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return co.edu.upb.grpc.NodoProcesamientoProto.internal_static_nodoprocesamiento_EstadoNodoResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return co.edu.upb.grpc.NodoProcesamientoProto.internal_static_nodoprocesamiento_EstadoNodoResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              co.edu.upb.grpc.EstadoNodoResponse.class, co.edu.upb.grpc.EstadoNodoResponse.Builder.class);
    }

    // Construct using co.edu.upb.grpc.EstadoNodoResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      idNodo_ = "";
      activo_ = false;
      capacidadMaxima_ = 0;
      cargaActual_ = 0;
      capacidadDisponible_ = 0;
      hilosConfigurados_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return co.edu.upb.grpc.NodoProcesamientoProto.internal_static_nodoprocesamiento_EstadoNodoResponse_descriptor;
    }

    @java.lang.Override
    public co.edu.upb.grpc.EstadoNodoResponse getDefaultInstanceForType() {
      return co.edu.upb.grpc.EstadoNodoResponse.getDefaultInstance();
    }

    @java.lang.Override
    public co.edu.upb.grpc.EstadoNodoResponse build() {
      co.edu.upb.grpc.EstadoNodoResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public co.edu.upb.grpc.EstadoNodoResponse buildPartial() {
      co.edu.upb.grpc.EstadoNodoResponse result = new co.edu.upb.grpc.EstadoNodoResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(co.edu.upb.grpc.EstadoNodoResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.idNodo_ = idNodo_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.activo_ = activo_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.capacidadMaxima_ = capacidadMaxima_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.cargaActual_ = cargaActual_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.capacidadDisponible_ = capacidadDisponible_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.hilosConfigurados_ = hilosConfigurados_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof co.edu.upb.grpc.EstadoNodoResponse) {
        return mergeFrom((co.edu.upb.grpc.EstadoNodoResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(co.edu.upb.grpc.EstadoNodoResponse other) {
      if (other == co.edu.upb.grpc.EstadoNodoResponse.getDefaultInstance()) return this;
      if (!other.getIdNodo().isEmpty()) {
        idNodo_ = other.idNodo_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getActivo() != false) {
        setActivo(other.getActivo());
      }
      if (other.getCapacidadMaxima() != 0) {
        setCapacidadMaxima(other.getCapacidadMaxima());
      }
      if (other.getCargaActual() != 0) {
        setCargaActual(other.getCargaActual());
      }
      if (other.getCapacidadDisponible() != 0) {
        setCapacidadDisponible(other.getCapacidadDisponible());
      }
      if (other.getHilosConfigurados() != 0) {
        setHilosConfigurados(other.getHilosConfigurados());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              idNodo_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              activo_ = input.readBool();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              capacidadMaxima_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              cargaActual_ = input.readInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              capacidadDisponible_ = input.readInt32();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 48: {
              hilosConfigurados_ = input.readInt32();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object idNodo_ = "";
    /**
     * <code>string idNodo = 1;</code>
     * @return The idNodo.
     */
    public java.lang.String getIdNodo() {
      java.lang.Object ref = idNodo_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        idNodo_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string idNodo = 1;</code>
     * @return The bytes for idNodo.
     */
    public com.google.protobuf.ByteString
        getIdNodoBytes() {
      java.lang.Object ref = idNodo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        idNodo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string idNodo = 1;</code>
     * @param value The idNodo to set.
     * @return This builder for chaining.
     */
    public Builder setIdNodo(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      idNodo_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string idNodo = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearIdNodo() {
      idNodo_ = getDefaultInstance().getIdNodo();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string idNodo = 1;</code>
     * @param value The bytes for idNodo to set.
     * @return This builder for chaining.
     */
    public Builder setIdNodoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      idNodo_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private boolean activo_ ;
    /**
     * <code>bool activo = 2;</code>
     * @return The activo.
     */
    @java.lang.Override
    public boolean getActivo() {
      return activo_;
    }
    /**
     * <code>bool activo = 2;</code>
     * @param value The activo to set.
     * @return This builder for chaining.
     */
    public Builder setActivo(boolean value) {

      activo_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>bool activo = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearActivo() {
      bitField0_ = (bitField0_ & ~0x00000002);
      activo_ = false;
      onChanged();
      return this;
    }

    private int capacidadMaxima_ ;
    /**
     * <code>int32 capacidadMaxima = 3;</code>
     * @return The capacidadMaxima.
     */
    @java.lang.Override
    public int getCapacidadMaxima() {
      return capacidadMaxima_;
    }
    /**
     * <code>int32 capacidadMaxima = 3;</code>
     * @param value The capacidadMaxima to set.
     * @return This builder for chaining.
     */
    public Builder setCapacidadMaxima(int value) {

      capacidadMaxima_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int32 capacidadMaxima = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearCapacidadMaxima() {
      bitField0_ = (bitField0_ & ~0x00000004);
      capacidadMaxima_ = 0;
      onChanged();
      return this;
    }

    private int cargaActual_ ;
    /**
     * <code>int32 cargaActual = 4;</code>
     * @return The cargaActual.
     */
    @java.lang.Override
    public int getCargaActual() {
      return cargaActual_;
    }
    /**
     * <code>int32 cargaActual = 4;</code>
     * @param value The cargaActual to set.
     * @return This builder for chaining.
     */
    public Builder setCargaActual(int value) {

      cargaActual_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int32 cargaActual = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearCargaActual() {
      bitField0_ = (bitField0_ & ~0x00000008);
      cargaActual_ = 0;
      onChanged();
      return this;
    }

    private int capacidadDisponible_ ;
    /**
     * <code>int32 capacidadDisponible = 5;</code>
     * @return The capacidadDisponible.
     */
    @java.lang.Override
    public int getCapacidadDisponible() {
      return capacidadDisponible_;
    }
    /**
     * <code>int32 capacidadDisponible = 5;</code>
     * @param value The capacidadDisponible to set.
     * @return This builder for chaining.
     */
    public Builder setCapacidadDisponible(int value) {

      capacidadDisponible_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>int32 capacidadDisponible = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearCapacidadDisponible() {
      bitField0_ = (bitField0_ & ~0x00000010);
      capacidadDisponible_ = 0;
      onChanged();
      return this;
    }

    private int hilosConfigurados_ ;
    /**
     * <code>int32 hilosConfigurados = 6;</code>
     * @return The hilosConfigurados.
     */
    @java.lang.Override
    public int getHilosConfigurados() {
      return hilosConfigurados_;
    }
    /**
     * <code>int32 hilosConfigurados = 6;</code>
     * @param value The hilosConfigurados to set.
     * @return This builder for chaining.
     */
    public Builder setHilosConfigurados(int value) {

      hilosConfigurados_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>int32 hilosConfigurados = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearHilosConfigurados() {
      bitField0_ = (bitField0_ & ~0x00000020);
      hilosConfigurados_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:nodoprocesamiento.EstadoNodoResponse)
  }

  // @@protoc_insertion_point(class_scope:nodoprocesamiento.EstadoNodoResponse)
  private static final co.edu.upb.grpc.EstadoNodoResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new co.edu.upb.grpc.EstadoNodoResponse();
  }

  public static co.edu.upb.grpc.EstadoNodoResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<EstadoNodoResponse>
      PARSER = new com.google.protobuf.AbstractParser<EstadoNodoResponse>() {
    @java.lang.Override
    public EstadoNodoResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<EstadoNodoResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<EstadoNodoResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public co.edu.upb.grpc.EstadoNodoResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

