// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nodo_procesamiento.proto

// Protobuf Java Version: 3.25.3
package co.edu.upb.grpc;

public interface EstadoNodoRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:nodoprocesamiento.EstadoNodoRequest)
    com.google.protobuf.MessageOrBuilder {
}
