// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nodo_procesamiento.proto

// Protobuf Java Version: 3.25.3
package co.edu.upb.grpc;

public interface MetricasNodoRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:nodoprocesamiento.MetricasNodoRequest)
    com.google.protobuf.MessageOrBuilder {
}
