// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nodo_procesamiento.proto

// Protobuf Java Version: 3.25.3
package co.edu.upb.grpc;

/**
 * Protobuf type {@code nodoprocesamiento.MetricasNodoResponse}
 */
public final class MetricasNodoResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:nodoprocesamiento.MetricasNodoResponse)
    MetricasNodoResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MetricasNodoResponse.newBuilder() to construct.
  private MetricasNodoResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MetricasNodoResponse() {
    idNodo_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new MetricasNodoResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return co.edu.upb.grpc.NodoProcesamientoProto.internal_static_nodoprocesamiento_MetricasNodoResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return co.edu.upb.grpc.NodoProcesamientoProto.internal_static_nodoprocesamiento_MetricasNodoResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            co.edu.upb.grpc.MetricasNodoResponse.class, co.edu.upb.grpc.MetricasNodoResponse.Builder.class);
  }

  public static final int IDNODO_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object idNodo_ = "";
  /**
   * <code>string idNodo = 1;</code>
   * @return The idNodo.
   */
  @java.lang.Override
  public java.lang.String getIdNodo() {
    java.lang.Object ref = idNodo_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      idNodo_ = s;
      return s;
    }
  }
  /**
   * <code>string idNodo = 1;</code>
   * @return The bytes for idNodo.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdNodoBytes() {
    java.lang.Object ref = idNodo_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      idNodo_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TRABAJOSRECIBIDOS_FIELD_NUMBER = 2;
  private int trabajosRecibidos_ = 0;
  /**
   * <code>int32 trabajosRecibidos = 2;</code>
   * @return The trabajosRecibidos.
   */
  @java.lang.Override
  public int getTrabajosRecibidos() {
    return trabajosRecibidos_;
  }

  public static final int TRABAJOSCOMPLETADOS_FIELD_NUMBER = 3;
  private int trabajosCompletados_ = 0;
  /**
   * <code>int32 trabajosCompletados = 3;</code>
   * @return The trabajosCompletados.
   */
  @java.lang.Override
  public int getTrabajosCompletados() {
    return trabajosCompletados_;
  }

  public static final int TRABAJOSFALLIDOS_FIELD_NUMBER = 4;
  private int trabajosFallidos_ = 0;
  /**
   * <code>int32 trabajosFallidos = 4;</code>
   * @return The trabajosFallidos.
   */
  @java.lang.Override
  public int getTrabajosFallidos() {
    return trabajosFallidos_;
  }

  public static final int TIEMPOTOTALPROCESAMIENTOMS_FIELD_NUMBER = 5;
  private long tiempoTotalProcesamientoMs_ = 0L;
  /**
   * <code>int64 tiempoTotalProcesamientoMs = 5;</code>
   * @return The tiempoTotalProcesamientoMs.
   */
  @java.lang.Override
  public long getTiempoTotalProcesamientoMs() {
    return tiempoTotalProcesamientoMs_;
  }

  public static final int TIEMPOPROMEDIOPROCESAMIENTOMS_FIELD_NUMBER = 6;
  private double tiempoPromedioProcesamientoMs_ = 0D;
  /**
   * <code>double tiempoPromedioProcesamientoMs = 6;</code>
   * @return The tiempoPromedioProcesamientoMs.
   */
  @java.lang.Override
  public double getTiempoPromedioProcesamientoMs() {
    return tiempoPromedioProcesamientoMs_;
  }

  public static final int CARGAACTUAL_FIELD_NUMBER = 7;
  private int cargaActual_ = 0;
  /**
   * <code>int32 cargaActual = 7;</code>
   * @return The cargaActual.
   */
  @java.lang.Override
  public int getCargaActual() {
    return cargaActual_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(idNodo_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, idNodo_);
    }
    if (trabajosRecibidos_ != 0) {
      output.writeInt32(2, trabajosRecibidos_);
    }
    if (trabajosCompletados_ != 0) {
      output.writeInt32(3, trabajosCompletados_);
    }
    if (trabajosFallidos_ != 0) {
      output.writeInt32(4, trabajosFallidos_);
    }
    if (tiempoTotalProcesamientoMs_ != 0L) {
      output.writeInt64(5, tiempoTotalProcesamientoMs_);
    }
    if (java.lang.Double.doubleToRawLongBits(tiempoPromedioProcesamientoMs_) != 0) {
      output.writeDouble(6, tiempoPromedioProcesamientoMs_);
    }
    if (cargaActual_ != 0) {
      output.writeInt32(7, cargaActual_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(idNodo_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, idNodo_);
    }
    if (trabajosRecibidos_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, trabajosRecibidos_);
    }
    if (trabajosCompletados_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, trabajosCompletados_);
    }
    if (trabajosFallidos_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, trabajosFallidos_);
    }
    if (tiempoTotalProcesamientoMs_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, tiempoTotalProcesamientoMs_);
    }
    if (java.lang.Double.doubleToRawLongBits(tiempoPromedioProcesamientoMs_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(6, tiempoPromedioProcesamientoMs_);
    }
    if (cargaActual_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(7, cargaActual_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof co.edu.upb.grpc.MetricasNodoResponse)) {
      return super.equals(obj);
    }
    co.edu.upb.grpc.MetricasNodoResponse other = (co.edu.upb.grpc.MetricasNodoResponse) obj;

    if (!getIdNodo()
        .equals(other.getIdNodo())) return false;
    if (getTrabajosRecibidos()
        != other.getTrabajosRecibidos()) return false;
    if (getTrabajosCompletados()
        != other.getTrabajosCompletados()) return false;
    if (getTrabajosFallidos()
        != other.getTrabajosFallidos()) return false;
    if (getTiempoTotalProcesamientoMs()
        != other.getTiempoTotalProcesamientoMs()) return false;
    if (java.lang.Double.doubleToLongBits(getTiempoPromedioProcesamientoMs())
        != java.lang.Double.doubleToLongBits(
            other.getTiempoPromedioProcesamientoMs())) return false;
    if (getCargaActual()
        != other.getCargaActual()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + IDNODO_FIELD_NUMBER;
    hash = (53 * hash) + getIdNodo().hashCode();
    hash = (37 * hash) + TRABAJOSRECIBIDOS_FIELD_NUMBER;
    hash = (53 * hash) + getTrabajosRecibidos();
    hash = (37 * hash) + TRABAJOSCOMPLETADOS_FIELD_NUMBER;
    hash = (53 * hash) + getTrabajosCompletados();
    hash = (37 * hash) + TRABAJOSFALLIDOS_FIELD_NUMBER;
    hash = (53 * hash) + getTrabajosFallidos();
    hash = (37 * hash) + TIEMPOTOTALPROCESAMIENTOMS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTiempoTotalProcesamientoMs());
    hash = (37 * hash) + TIEMPOPROMEDIOPROCESAMIENTOMS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getTiempoPromedioProcesamientoMs()));
    hash = (37 * hash) + CARGAACTUAL_FIELD_NUMBER;
    hash = (53 * hash) + getCargaActual();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static co.edu.upb.grpc.MetricasNodoResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static co.edu.upb.grpc.MetricasNodoResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static co.edu.upb.grpc.MetricasNodoResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static co.edu.upb.grpc.MetricasNodoResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static co.edu.upb.grpc.MetricasNodoResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static co.edu.upb.grpc.MetricasNodoResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static co.edu.upb.grpc.MetricasNodoResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static co.edu.upb.grpc.MetricasNodoResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static co.edu.upb.grpc.MetricasNodoResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static co.edu.upb.grpc.MetricasNodoResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static co.edu.upb.grpc.MetricasNodoResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static co.edu.upb.grpc.MetricasNodoResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(co.edu.upb.grpc.MetricasNodoResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code nodoprocesamiento.MetricasNodoResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:nodoprocesamiento.MetricasNodoResponse)
      co.edu.upb.grpc.MetricasNodoResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return co.edu.upb.grpc.NodoProcesamientoProto.internal_static_nodoprocesamiento_MetricasNodoResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return co.edu.upb.grpc.NodoProcesamientoProto.internal_static_nodoprocesamiento_MetricasNodoResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              co.edu.upb.grpc.MetricasNodoResponse.class, co.edu.upb.grpc.MetricasNodoResponse.Builder.class);
    }

    // Construct using co.edu.upb.grpc.MetricasNodoResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      idNodo_ = "";
      trabajosRecibidos_ = 0;
      trabajosCompletados_ = 0;
      trabajosFallidos_ = 0;
      tiempoTotalProcesamientoMs_ = 0L;
      tiempoPromedioProcesamientoMs_ = 0D;
      cargaActual_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return co.edu.upb.grpc.NodoProcesamientoProto.internal_static_nodoprocesamiento_MetricasNodoResponse_descriptor;
    }

    @java.lang.Override
    public co.edu.upb.grpc.MetricasNodoResponse getDefaultInstanceForType() {
      return co.edu.upb.grpc.MetricasNodoResponse.getDefaultInstance();
    }

    @java.lang.Override
    public co.edu.upb.grpc.MetricasNodoResponse build() {
      co.edu.upb.grpc.MetricasNodoResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public co.edu.upb.grpc.MetricasNodoResponse buildPartial() {
      co.edu.upb.grpc.MetricasNodoResponse result = new co.edu.upb.grpc.MetricasNodoResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(co.edu.upb.grpc.MetricasNodoResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.idNodo_ = idNodo_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.trabajosRecibidos_ = trabajosRecibidos_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.trabajosCompletados_ = trabajosCompletados_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.trabajosFallidos_ = trabajosFallidos_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.tiempoTotalProcesamientoMs_ = tiempoTotalProcesamientoMs_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.tiempoPromedioProcesamientoMs_ = tiempoPromedioProcesamientoMs_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.cargaActual_ = cargaActual_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof co.edu.upb.grpc.MetricasNodoResponse) {
        return mergeFrom((co.edu.upb.grpc.MetricasNodoResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(co.edu.upb.grpc.MetricasNodoResponse other) {
      if (other == co.edu.upb.grpc.MetricasNodoResponse.getDefaultInstance()) return this;
      if (!other.getIdNodo().isEmpty()) {
        idNodo_ = other.idNodo_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getTrabajosRecibidos() != 0) {
        setTrabajosRecibidos(other.getTrabajosRecibidos());
      }
      if (other.getTrabajosCompletados() != 0) {
        setTrabajosCompletados(other.getTrabajosCompletados());
      }
      if (other.getTrabajosFallidos() != 0) {
        setTrabajosFallidos(other.getTrabajosFallidos());
      }
      if (other.getTiempoTotalProcesamientoMs() != 0L) {
        setTiempoTotalProcesamientoMs(other.getTiempoTotalProcesamientoMs());
      }
      if (other.getTiempoPromedioProcesamientoMs() != 0D) {
        setTiempoPromedioProcesamientoMs(other.getTiempoPromedioProcesamientoMs());
      }
      if (other.getCargaActual() != 0) {
        setCargaActual(other.getCargaActual());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              idNodo_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              trabajosRecibidos_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              trabajosCompletados_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              trabajosFallidos_ = input.readInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              tiempoTotalProcesamientoMs_ = input.readInt64();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 49: {
              tiempoPromedioProcesamientoMs_ = input.readDouble();
              bitField0_ |= 0x00000020;
              break;
            } // case 49
            case 56: {
              cargaActual_ = input.readInt32();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object idNodo_ = "";
    /**
     * <code>string idNodo = 1;</code>
     * @return The idNodo.
     */
    public java.lang.String getIdNodo() {
      java.lang.Object ref = idNodo_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        idNodo_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string idNodo = 1;</code>
     * @return The bytes for idNodo.
     */
    public com.google.protobuf.ByteString
        getIdNodoBytes() {
      java.lang.Object ref = idNodo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        idNodo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string idNodo = 1;</code>
     * @param value The idNodo to set.
     * @return This builder for chaining.
     */
    public Builder setIdNodo(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      idNodo_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string idNodo = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearIdNodo() {
      idNodo_ = getDefaultInstance().getIdNodo();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string idNodo = 1;</code>
     * @param value The bytes for idNodo to set.
     * @return This builder for chaining.
     */
    public Builder setIdNodoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      idNodo_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private int trabajosRecibidos_ ;
    /**
     * <code>int32 trabajosRecibidos = 2;</code>
     * @return The trabajosRecibidos.
     */
    @java.lang.Override
    public int getTrabajosRecibidos() {
      return trabajosRecibidos_;
    }
    /**
     * <code>int32 trabajosRecibidos = 2;</code>
     * @param value The trabajosRecibidos to set.
     * @return This builder for chaining.
     */
    public Builder setTrabajosRecibidos(int value) {

      trabajosRecibidos_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int32 trabajosRecibidos = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTrabajosRecibidos() {
      bitField0_ = (bitField0_ & ~0x00000002);
      trabajosRecibidos_ = 0;
      onChanged();
      return this;
    }

    private int trabajosCompletados_ ;
    /**
     * <code>int32 trabajosCompletados = 3;</code>
     * @return The trabajosCompletados.
     */
    @java.lang.Override
    public int getTrabajosCompletados() {
      return trabajosCompletados_;
    }
    /**
     * <code>int32 trabajosCompletados = 3;</code>
     * @param value The trabajosCompletados to set.
     * @return This builder for chaining.
     */
    public Builder setTrabajosCompletados(int value) {

      trabajosCompletados_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int32 trabajosCompletados = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTrabajosCompletados() {
      bitField0_ = (bitField0_ & ~0x00000004);
      trabajosCompletados_ = 0;
      onChanged();
      return this;
    }

    private int trabajosFallidos_ ;
    /**
     * <code>int32 trabajosFallidos = 4;</code>
     * @return The trabajosFallidos.
     */
    @java.lang.Override
    public int getTrabajosFallidos() {
      return trabajosFallidos_;
    }
    /**
     * <code>int32 trabajosFallidos = 4;</code>
     * @param value The trabajosFallidos to set.
     * @return This builder for chaining.
     */
    public Builder setTrabajosFallidos(int value) {

      trabajosFallidos_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int32 trabajosFallidos = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearTrabajosFallidos() {
      bitField0_ = (bitField0_ & ~0x00000008);
      trabajosFallidos_ = 0;
      onChanged();
      return this;
    }

    private long tiempoTotalProcesamientoMs_ ;
    /**
     * <code>int64 tiempoTotalProcesamientoMs = 5;</code>
     * @return The tiempoTotalProcesamientoMs.
     */
    @java.lang.Override
    public long getTiempoTotalProcesamientoMs() {
      return tiempoTotalProcesamientoMs_;
    }
    /**
     * <code>int64 tiempoTotalProcesamientoMs = 5;</code>
     * @param value The tiempoTotalProcesamientoMs to set.
     * @return This builder for chaining.
     */
    public Builder setTiempoTotalProcesamientoMs(long value) {

      tiempoTotalProcesamientoMs_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>int64 tiempoTotalProcesamientoMs = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearTiempoTotalProcesamientoMs() {
      bitField0_ = (bitField0_ & ~0x00000010);
      tiempoTotalProcesamientoMs_ = 0L;
      onChanged();
      return this;
    }

    private double tiempoPromedioProcesamientoMs_ ;
    /**
     * <code>double tiempoPromedioProcesamientoMs = 6;</code>
     * @return The tiempoPromedioProcesamientoMs.
     */
    @java.lang.Override
    public double getTiempoPromedioProcesamientoMs() {
      return tiempoPromedioProcesamientoMs_;
    }
    /**
     * <code>double tiempoPromedioProcesamientoMs = 6;</code>
     * @param value The tiempoPromedioProcesamientoMs to set.
     * @return This builder for chaining.
     */
    public Builder setTiempoPromedioProcesamientoMs(double value) {

      tiempoPromedioProcesamientoMs_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>double tiempoPromedioProcesamientoMs = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearTiempoPromedioProcesamientoMs() {
      bitField0_ = (bitField0_ & ~0x00000020);
      tiempoPromedioProcesamientoMs_ = 0D;
      onChanged();
      return this;
    }

    private int cargaActual_ ;
    /**
     * <code>int32 cargaActual = 7;</code>
     * @return The cargaActual.
     */
    @java.lang.Override
    public int getCargaActual() {
      return cargaActual_;
    }
    /**
     * <code>int32 cargaActual = 7;</code>
     * @param value The cargaActual to set.
     * @return This builder for chaining.
     */
    public Builder setCargaActual(int value) {

      cargaActual_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>int32 cargaActual = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearCargaActual() {
      bitField0_ = (bitField0_ & ~0x00000040);
      cargaActual_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:nodoprocesamiento.MetricasNodoResponse)
  }

  // @@protoc_insertion_point(class_scope:nodoprocesamiento.MetricasNodoResponse)
  private static final co.edu.upb.grpc.MetricasNodoResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new co.edu.upb.grpc.MetricasNodoResponse();
  }

  public static co.edu.upb.grpc.MetricasNodoResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MetricasNodoResponse>
      PARSER = new com.google.protobuf.AbstractParser<MetricasNodoResponse>() {
    @java.lang.Override
    public MetricasNodoResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<MetricasNodoResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MetricasNodoResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public co.edu.upb.grpc.MetricasNodoResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

