// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nodo_procesamiento.proto

// Protobuf Java Version: 3.25.3
package co.edu.upb.grpc;

public interface RespuestaRecepcionTrabajosOrBuilder extends
    // @@protoc_insertion_point(interface_extends:nodoprocesamiento.RespuestaRecepcionTrabajos)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 aceptados = 1;</code>
   * @return The aceptados.
   */
  int getAceptados();

  /**
   * <code>int32 rechazados = 2;</code>
   * @return The rechazados.
   */
  int getRechazados();

  /**
   * <code>string mensaje = 3;</code>
   * @return The mensaje.
   */
  java.lang.String getMensaje();
  /**
   * <code>string mensaje = 3;</code>
   * @return The bytes for mensaje.
   */
  com.google.protobuf.ByteString
      getMensajeBytes();
}
