// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nodo_procesamiento.proto

// Protobuf Java Version: 3.25.3
package co.edu.upb.grpc;

public interface TransformacionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:nodoprocesamiento.TransformacionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string tipo = 1;</code>
   * @return The tipo.
   */
  java.lang.String getTipo();
  /**
   * <code>string tipo = 1;</code>
   * @return The bytes for tipo.
   */
  com.google.protobuf.ByteString
      getTipoBytes();

  /**
   * <code>string valor = 2;</code>
   * @return The valor.
   */
  java.lang.String getValor();
  /**
   * <code>string valor = 2;</code>
   * @return The bytes for valor.
   */
  com.google.protobuf.ByteString
      getValorBytes();
}
