// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nodo_procesamiento.proto

// Protobuf Java Version: 3.25.3
package co.edu.upb.grpc;

/**
 * Protobuf type {@code nodoprocesamiento.TransformacionRequest}
 */
public final class TransformacionRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:nodoprocesamiento.TransformacionRequest)
    TransformacionRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TransformacionRequest.newBuilder() to construct.
  private TransformacionRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TransformacionRequest() {
    tipo_ = "";
    valor_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new TransformacionRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return co.edu.upb.grpc.NodoProcesamientoProto.internal_static_nodoprocesamiento_TransformacionRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return co.edu.upb.grpc.NodoProcesamientoProto.internal_static_nodoprocesamiento_TransformacionRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            co.edu.upb.grpc.TransformacionRequest.class, co.edu.upb.grpc.TransformacionRequest.Builder.class);
  }

  public static final int TIPO_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object tipo_ = "";
  /**
   * <code>string tipo = 1;</code>
   * @return The tipo.
   */
  @java.lang.Override
  public java.lang.String getTipo() {
    java.lang.Object ref = tipo_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tipo_ = s;
      return s;
    }
  }
  /**
   * <code>string tipo = 1;</code>
   * @return The bytes for tipo.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTipoBytes() {
    java.lang.Object ref = tipo_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tipo_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VALOR_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object valor_ = "";
  /**
   * <code>string valor = 2;</code>
   * @return The valor.
   */
  @java.lang.Override
  public java.lang.String getValor() {
    java.lang.Object ref = valor_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      valor_ = s;
      return s;
    }
  }
  /**
   * <code>string valor = 2;</code>
   * @return The bytes for valor.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getValorBytes() {
    java.lang.Object ref = valor_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      valor_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tipo_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, tipo_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(valor_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, valor_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tipo_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, tipo_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(valor_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, valor_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof co.edu.upb.grpc.TransformacionRequest)) {
      return super.equals(obj);
    }
    co.edu.upb.grpc.TransformacionRequest other = (co.edu.upb.grpc.TransformacionRequest) obj;

    if (!getTipo()
        .equals(other.getTipo())) return false;
    if (!getValor()
        .equals(other.getValor())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TIPO_FIELD_NUMBER;
    hash = (53 * hash) + getTipo().hashCode();
    hash = (37 * hash) + VALOR_FIELD_NUMBER;
    hash = (53 * hash) + getValor().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static co.edu.upb.grpc.TransformacionRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static co.edu.upb.grpc.TransformacionRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static co.edu.upb.grpc.TransformacionRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static co.edu.upb.grpc.TransformacionRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static co.edu.upb.grpc.TransformacionRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static co.edu.upb.grpc.TransformacionRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static co.edu.upb.grpc.TransformacionRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static co.edu.upb.grpc.TransformacionRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static co.edu.upb.grpc.TransformacionRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static co.edu.upb.grpc.TransformacionRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static co.edu.upb.grpc.TransformacionRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static co.edu.upb.grpc.TransformacionRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(co.edu.upb.grpc.TransformacionRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code nodoprocesamiento.TransformacionRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:nodoprocesamiento.TransformacionRequest)
      co.edu.upb.grpc.TransformacionRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return co.edu.upb.grpc.NodoProcesamientoProto.internal_static_nodoprocesamiento_TransformacionRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return co.edu.upb.grpc.NodoProcesamientoProto.internal_static_nodoprocesamiento_TransformacionRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              co.edu.upb.grpc.TransformacionRequest.class, co.edu.upb.grpc.TransformacionRequest.Builder.class);
    }

    // Construct using co.edu.upb.grpc.TransformacionRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      tipo_ = "";
      valor_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return co.edu.upb.grpc.NodoProcesamientoProto.internal_static_nodoprocesamiento_TransformacionRequest_descriptor;
    }

    @java.lang.Override
    public co.edu.upb.grpc.TransformacionRequest getDefaultInstanceForType() {
      return co.edu.upb.grpc.TransformacionRequest.getDefaultInstance();
    }

    @java.lang.Override
    public co.edu.upb.grpc.TransformacionRequest build() {
      co.edu.upb.grpc.TransformacionRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public co.edu.upb.grpc.TransformacionRequest buildPartial() {
      co.edu.upb.grpc.TransformacionRequest result = new co.edu.upb.grpc.TransformacionRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(co.edu.upb.grpc.TransformacionRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.tipo_ = tipo_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.valor_ = valor_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof co.edu.upb.grpc.TransformacionRequest) {
        return mergeFrom((co.edu.upb.grpc.TransformacionRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(co.edu.upb.grpc.TransformacionRequest other) {
      if (other == co.edu.upb.grpc.TransformacionRequest.getDefaultInstance()) return this;
      if (!other.getTipo().isEmpty()) {
        tipo_ = other.tipo_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getValor().isEmpty()) {
        valor_ = other.valor_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              tipo_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              valor_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object tipo_ = "";
    /**
     * <code>string tipo = 1;</code>
     * @return The tipo.
     */
    public java.lang.String getTipo() {
      java.lang.Object ref = tipo_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tipo_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string tipo = 1;</code>
     * @return The bytes for tipo.
     */
    public com.google.protobuf.ByteString
        getTipoBytes() {
      java.lang.Object ref = tipo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tipo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string tipo = 1;</code>
     * @param value The tipo to set.
     * @return This builder for chaining.
     */
    public Builder setTipo(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      tipo_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string tipo = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTipo() {
      tipo_ = getDefaultInstance().getTipo();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string tipo = 1;</code>
     * @param value The bytes for tipo to set.
     * @return This builder for chaining.
     */
    public Builder setTipoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      tipo_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object valor_ = "";
    /**
     * <code>string valor = 2;</code>
     * @return The valor.
     */
    public java.lang.String getValor() {
      java.lang.Object ref = valor_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        valor_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string valor = 2;</code>
     * @return The bytes for valor.
     */
    public com.google.protobuf.ByteString
        getValorBytes() {
      java.lang.Object ref = valor_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        valor_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string valor = 2;</code>
     * @param value The valor to set.
     * @return This builder for chaining.
     */
    public Builder setValor(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      valor_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string valor = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearValor() {
      valor_ = getDefaultInstance().getValor();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string valor = 2;</code>
     * @param value The bytes for valor to set.
     * @return This builder for chaining.
     */
    public Builder setValorBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      valor_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:nodoprocesamiento.TransformacionRequest)
  }

  // @@protoc_insertion_point(class_scope:nodoprocesamiento.TransformacionRequest)
  private static final co.edu.upb.grpc.TransformacionRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new co.edu.upb.grpc.TransformacionRequest();
  }

  public static co.edu.upb.grpc.TransformacionRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TransformacionRequest>
      PARSER = new com.google.protobuf.AbstractParser<TransformacionRequest>() {
    @java.lang.Override
    public TransformacionRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<TransformacionRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TransformacionRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public co.edu.upb.grpc.TransformacionRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

