server.port=8080

db.url=jdbc:mysql://shortline.proxy.rlwy.net:16423/railway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
db.user=root
db.password=osHubhnKSgtRJTweZvryMgpaZkLiVLFI

auth.base.url=http://visionix-auth.railway.internal:8082