server.port=8082

db.url=${DB_URL}
db.user=${DB_USER}
db.password=${DB_PASSWORD}

jwt.secret=${JWT_SECRET}
jwt.expiration.minutes=${JWT_EXPIRATION_MINUTES}

verification.code.expiration.minutes=${VERIFICATION_CODE_EXPIRATION_MINUTES}

mail.host=${MAIL_HOST}
mail.port=${MAIL_PORT}
mail.username=${MAIL_USERNAME}
mail.password=${MAIL_PASSWORD}
mail.from=${MAIL_FROM}