server.port=8082

db.url=jdbc:mysql://mainline.proxy.rlwy.net:27061/railway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
db.user=root
db.password=tfvUeYleNKmaZexHVxEMquchDmJBcMVv

jwt.secret=VisionixAuthSuperSecretKey2026UPBProduccionMuySegura123456789
jwt.expiration.minutes=60

verification.code.expiration.minutes=10

mail.host=smtp.gmail.com
mail.port=465
mail.username=visionixupb@gmail.com
mail.password=ywsl oidb kynm hwug
mail.from=visionixupb@gmail.com