server.port=8082

db.url=jdbc:mysql://mainline.proxy.rlwy.net:27061/railway
db.user=root
db.password=tfvUeYleNKmaZexHVxEMquchDmJBcMVv

jwt.secret=visionix_auth_super_secret_key_2026_upb_segura
jwt.expiration.minutes=60

db.url=jdbc:mysql://mainline.proxy.rlwy.net:27061/railway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC

verification.code.expiration.minutes=10

mail.host=smtp.gmail.com
mail.port=587
mail.username=visionixupb@gmail.com
mail.password=ywsl oidb kynm hwug
mail.from=visionixupb@gmail.com