// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nodo_procesamiento.proto

// Protobuf Java Version: 3.25.3
package co.edu.upb.grpc;

public interface EstadoNodoResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:nodoprocesamiento.EstadoNodoResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string idNodo = 1;</code>
   * @return The idNodo.
   */
  java.lang.String getIdNodo();
  /**
   * <code>string idNodo = 1;</code>
   * @return The bytes for idNodo.
   */
  com.google.protobuf.ByteString
      getIdNodoBytes();

  /**
   * <code>bool activo = 2;</code>
   * @return The activo.
   */
  boolean getActivo();

  /**
   * <code>int32 capacidadMaxima = 3;</code>
   * @return The capacidadMaxima.
   */
  int getCapacidadMaxima();

  /**
   * <code>int32 cargaActual = 4;</code>
   * @return The cargaActual.
   */
  int getCargaActual();

  /**
   * <code>int32 capacidadDisponible = 5;</code>
   * @return The capacidadDisponible.
   */
  int getCapacidadDisponible();

  /**
   * <code>int32 hilosConfigurados = 6;</code>
   * @return The hilosConfigurados.
   */
  int getHilosConfigurados();
}
