// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nodo_procesamiento.proto

// Protobuf Java Version: 3.25.3
package co.edu.upb.grpc;

public interface MetricasNodoResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:nodoprocesamiento.MetricasNodoResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string idNodo = 1;</code>
   * @return The idNodo.
   */
  java.lang.String getIdNodo();
  /**
   * <code>string idNodo = 1;</code>
   * @return The bytes for idNodo.
   */
  com.google.protobuf.ByteString
      getIdNodoBytes();

  /**
   * <code>int32 trabajosRecibidos = 2;</code>
   * @return The trabajosRecibidos.
   */
  int getTrabajosRecibidos();

  /**
   * <code>int32 trabajosCompletados = 3;</code>
   * @return The trabajosCompletados.
   */
  int getTrabajosCompletados();

  /**
   * <code>int32 trabajosFallidos = 4;</code>
   * @return The trabajosFallidos.
   */
  int getTrabajosFallidos();

  /**
   * <code>int64 tiempoTotalProcesamientoMs = 5;</code>
   * @return The tiempoTotalProcesamientoMs.
   */
  long getTiempoTotalProcesamientoMs();

  /**
   * <code>double tiempoPromedioProcesamientoMs = 6;</code>
   * @return The tiempoPromedioProcesamientoMs.
   */
  double getTiempoPromedioProcesamientoMs();

  /**
   * <code>int32 cargaActual = 7;</code>
   * @return The cargaActual.
   */
  int getCargaActual();
}
