// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nodo_procesamiento.proto

// Protobuf Java Version: 3.25.3
package co.edu.upb.grpc;

public final class NodoProcesamientoProto {
  private NodoProcesamientoProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nodoprocesamiento_TransformacionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_nodoprocesamiento_TransformacionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nodoprocesamiento_TrabajoImagenRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_nodoprocesamiento_TrabajoImagenRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nodoprocesamiento_SolicitudTrabajosRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_nodoprocesamiento_SolicitudTrabajosRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nodoprocesamiento_RespuestaRecepcionTrabajos_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_nodoprocesamiento_RespuestaRecepcionTrabajos_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nodoprocesamiento_EstadoNodoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_nodoprocesamiento_EstadoNodoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nodoprocesamiento_EstadoNodoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_nodoprocesamiento_EstadoNodoResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nodoprocesamiento_MetricasNodoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_nodoprocesamiento_MetricasNodoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nodoprocesamiento_MetricasNodoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_nodoprocesamiento_MetricasNodoResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030nodo_procesamiento.proto\022\021nodoprocesam" +
      "iento\"4\n\025TransformacionRequest\022\014\n\004tipo\030\001" +
      " \001(\t\022\r\n\005valor\030\002 \001(\t\"\247\001\n\024TrabajoImagenReq" +
      "uest\022\016\n\006idLote\030\001 \001(\003\022\020\n\010idImagen\030\002 \001(\003\022\025" +
      "\n\rnombreArchivo\030\003 \001(\t\022\022\n\nrutaOrigen\030\004 \001(" +
      "\t\022B\n\020transformaciones\030\005 \003(\0132(.nodoproces" +
      "amiento.TransformacionRequest\"U\n\030Solicit" +
      "udTrabajosRequest\0229\n\010trabajos\030\001 \003(\0132\'.no" +
      "doprocesamiento.TrabajoImagenRequest\"T\n\032" +
      "RespuestaRecepcionTrabajos\022\021\n\taceptados\030" +
      "\001 \001(\005\022\022\n\nrechazados\030\002 \001(\005\022\017\n\007mensaje\030\003 \001" +
      "(\t\"\023\n\021EstadoNodoRequest\"\232\001\n\022EstadoNodoRe" +
      "sponse\022\016\n\006idNodo\030\001 \001(\t\022\016\n\006activo\030\002 \001(\010\022\027" +
      "\n\017capacidadMaxima\030\003 \001(\005\022\023\n\013cargaActual\030\004" +
      " \001(\005\022\033\n\023capacidadDisponible\030\005 \001(\005\022\031\n\021hil" +
      "osConfigurados\030\006 \001(\005\"\025\n\023MetricasNodoRequ" +
      "est\"\330\001\n\024MetricasNodoResponse\022\016\n\006idNodo\030\001" +
      " \001(\t\022\031\n\021trabajosRecibidos\030\002 \001(\005\022\033\n\023traba" +
      "josCompletados\030\003 \001(\005\022\030\n\020trabajosFallidos" +
      "\030\004 \001(\005\022\"\n\032tiempoTotalProcesamientoMs\030\005 \001" +
      "(\003\022%\n\035tiempoPromedioProcesamientoMs\030\006 \001(" +
      "\001\022\023\n\013cargaActual\030\007 \001(\0052\324\002\n\031ServicioNodoP" +
      "rocesamiento\022`\n\021ObtenerEstadoNodo\022$.nodo" +
      "procesamiento.EstadoNodoRequest\032%.nodopr" +
      "ocesamiento.EstadoNodoResponse\022f\n\023Obtene" +
      "rMetricasNodo\022&.nodoprocesamiento.Metric" +
      "asNodoRequest\032\'.nodoprocesamiento.Metric" +
      "asNodoResponse\022m\n\017RecibirTrabajos\022+.nodo" +
      "procesamiento.SolicitudTrabajosRequest\032-" +
      ".nodoprocesamiento.RespuestaRecepcionTra" +
      "bajosB+\n\017co.edu.upb.grpcB\026NodoProcesamie" +
      "ntoProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_nodoprocesamiento_TransformacionRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_nodoprocesamiento_TransformacionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_nodoprocesamiento_TransformacionRequest_descriptor,
        new java.lang.String[] { "Tipo", "Valor", });
    internal_static_nodoprocesamiento_TrabajoImagenRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_nodoprocesamiento_TrabajoImagenRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_nodoprocesamiento_TrabajoImagenRequest_descriptor,
        new java.lang.String[] { "IdLote", "IdImagen", "NombreArchivo", "RutaOrigen", "Transformaciones", });
    internal_static_nodoprocesamiento_SolicitudTrabajosRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_nodoprocesamiento_SolicitudTrabajosRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_nodoprocesamiento_SolicitudTrabajosRequest_descriptor,
        new java.lang.String[] { "Trabajos", });
    internal_static_nodoprocesamiento_RespuestaRecepcionTrabajos_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_nodoprocesamiento_RespuestaRecepcionTrabajos_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_nodoprocesamiento_RespuestaRecepcionTrabajos_descriptor,
        new java.lang.String[] { "Aceptados", "Rechazados", "Mensaje", });
    internal_static_nodoprocesamiento_EstadoNodoRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_nodoprocesamiento_EstadoNodoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_nodoprocesamiento_EstadoNodoRequest_descriptor,
        new java.lang.String[] { });
    internal_static_nodoprocesamiento_EstadoNodoResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_nodoprocesamiento_EstadoNodoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_nodoprocesamiento_EstadoNodoResponse_descriptor,
        new java.lang.String[] { "IdNodo", "Activo", "CapacidadMaxima", "CargaActual", "CapacidadDisponible", "HilosConfigurados", });
    internal_static_nodoprocesamiento_MetricasNodoRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_nodoprocesamiento_MetricasNodoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_nodoprocesamiento_MetricasNodoRequest_descriptor,
        new java.lang.String[] { });
    internal_static_nodoprocesamiento_MetricasNodoResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_nodoprocesamiento_MetricasNodoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_nodoprocesamiento_MetricasNodoResponse_descriptor,
        new java.lang.String[] { "IdNodo", "TrabajosRecibidos", "TrabajosCompletados", "TrabajosFallidos", "TiempoTotalProcesamientoMs", "TiempoPromedioProcesamientoMs", "CargaActual", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
