// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nodo_procesamiento.proto

// Protobuf Java Version: 3.25.3
package co.edu.upb.grpc;

/**
 * Protobuf type {@code nodoprocesamiento.RespuestaRecepcionTrabajos}
 */
public final class RespuestaRecepcionTrabajos extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:nodoprocesamiento.RespuestaRecepcionTrabajos)
    RespuestaRecepcionTrabajosOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RespuestaRecepcionTrabajos.newBuilder() to construct.
  private RespuestaRecepcionTrabajos(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RespuestaRecepcionTrabajos() {
    mensaje_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new RespuestaRecepcionTrabajos();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return co.edu.upb.grpc.NodoProcesamientoProto.internal_static_nodoprocesamiento_RespuestaRecepcionTrabajos_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return co.edu.upb.grpc.NodoProcesamientoProto.internal_static_nodoprocesamiento_RespuestaRecepcionTrabajos_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            co.edu.upb.grpc.RespuestaRecepcionTrabajos.class, co.edu.upb.grpc.RespuestaRecepcionTrabajos.Builder.class);
  }

  public static final int ACEPTADOS_FIELD_NUMBER = 1;
  private int aceptados_ = 0;
  /**
   * <code>int32 aceptados = 1;</code>
   * @return The aceptados.
   */
  @java.lang.Override
  public int getAceptados() {
    return aceptados_;
  }

  public static final int RECHAZADOS_FIELD_NUMBER = 2;
  private int rechazados_ = 0;
  /**
   * <code>int32 rechazados = 2;</code>
   * @return The rechazados.
   */
  @java.lang.Override
  public int getRechazados() {
    return rechazados_;
  }

  public static final int MENSAJE_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object mensaje_ = "";
  /**
   * <code>string mensaje = 3;</code>
   * @return The mensaje.
   */
  @java.lang.Override
  public java.lang.String getMensaje() {
    java.lang.Object ref = mensaje_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      mensaje_ = s;
      return s;
    }
  }
  /**
   * <code>string mensaje = 3;</code>
   * @return The bytes for mensaje.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMensajeBytes() {
    java.lang.Object ref = mensaje_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      mensaje_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (aceptados_ != 0) {
      output.writeInt32(1, aceptados_);
    }
    if (rechazados_ != 0) {
      output.writeInt32(2, rechazados_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(mensaje_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, mensaje_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (aceptados_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, aceptados_);
    }
    if (rechazados_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, rechazados_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(mensaje_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, mensaje_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof co.edu.upb.grpc.RespuestaRecepcionTrabajos)) {
      return super.equals(obj);
    }
    co.edu.upb.grpc.RespuestaRecepcionTrabajos other = (co.edu.upb.grpc.RespuestaRecepcionTrabajos) obj;

    if (getAceptados()
        != other.getAceptados()) return false;
    if (getRechazados()
        != other.getRechazados()) return false;
    if (!getMensaje()
        .equals(other.getMensaje())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ACEPTADOS_FIELD_NUMBER;
    hash = (53 * hash) + getAceptados();
    hash = (37 * hash) + RECHAZADOS_FIELD_NUMBER;
    hash = (53 * hash) + getRechazados();
    hash = (37 * hash) + MENSAJE_FIELD_NUMBER;
    hash = (53 * hash) + getMensaje().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static co.edu.upb.grpc.RespuestaRecepcionTrabajos parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static co.edu.upb.grpc.RespuestaRecepcionTrabajos parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static co.edu.upb.grpc.RespuestaRecepcionTrabajos parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static co.edu.upb.grpc.RespuestaRecepcionTrabajos parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static co.edu.upb.grpc.RespuestaRecepcionTrabajos parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static co.edu.upb.grpc.RespuestaRecepcionTrabajos parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static co.edu.upb.grpc.RespuestaRecepcionTrabajos parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static co.edu.upb.grpc.RespuestaRecepcionTrabajos parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static co.edu.upb.grpc.RespuestaRecepcionTrabajos parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static co.edu.upb.grpc.RespuestaRecepcionTrabajos parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static co.edu.upb.grpc.RespuestaRecepcionTrabajos parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static co.edu.upb.grpc.RespuestaRecepcionTrabajos parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(co.edu.upb.grpc.RespuestaRecepcionTrabajos prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code nodoprocesamiento.RespuestaRecepcionTrabajos}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:nodoprocesamiento.RespuestaRecepcionTrabajos)
      co.edu.upb.grpc.RespuestaRecepcionTrabajosOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return co.edu.upb.grpc.NodoProcesamientoProto.internal_static_nodoprocesamiento_RespuestaRecepcionTrabajos_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return co.edu.upb.grpc.NodoProcesamientoProto.internal_static_nodoprocesamiento_RespuestaRecepcionTrabajos_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              co.edu.upb.grpc.RespuestaRecepcionTrabajos.class, co.edu.upb.grpc.RespuestaRecepcionTrabajos.Builder.class);
    }

    // Construct using co.edu.upb.grpc.RespuestaRecepcionTrabajos.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      aceptados_ = 0;
      rechazados_ = 0;
      mensaje_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return co.edu.upb.grpc.NodoProcesamientoProto.internal_static_nodoprocesamiento_RespuestaRecepcionTrabajos_descriptor;
    }

    @java.lang.Override
    public co.edu.upb.grpc.RespuestaRecepcionTrabajos getDefaultInstanceForType() {
      return co.edu.upb.grpc.RespuestaRecepcionTrabajos.getDefaultInstance();
    }

    @java.lang.Override
    public co.edu.upb.grpc.RespuestaRecepcionTrabajos build() {
      co.edu.upb.grpc.RespuestaRecepcionTrabajos result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public co.edu.upb.grpc.RespuestaRecepcionTrabajos buildPartial() {
      co.edu.upb.grpc.RespuestaRecepcionTrabajos result = new co.edu.upb.grpc.RespuestaRecepcionTrabajos(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(co.edu.upb.grpc.RespuestaRecepcionTrabajos result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.aceptados_ = aceptados_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.rechazados_ = rechazados_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.mensaje_ = mensaje_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof co.edu.upb.grpc.RespuestaRecepcionTrabajos) {
        return mergeFrom((co.edu.upb.grpc.RespuestaRecepcionTrabajos)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(co.edu.upb.grpc.RespuestaRecepcionTrabajos other) {
      if (other == co.edu.upb.grpc.RespuestaRecepcionTrabajos.getDefaultInstance()) return this;
      if (other.getAceptados() != 0) {
        setAceptados(other.getAceptados());
      }
      if (other.getRechazados() != 0) {
        setRechazados(other.getRechazados());
      }
      if (!other.getMensaje().isEmpty()) {
        mensaje_ = other.mensaje_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              aceptados_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              rechazados_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              mensaje_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int aceptados_ ;
    /**
     * <code>int32 aceptados = 1;</code>
     * @return The aceptados.
     */
    @java.lang.Override
    public int getAceptados() {
      return aceptados_;
    }
    /**
     * <code>int32 aceptados = 1;</code>
     * @param value The aceptados to set.
     * @return This builder for chaining.
     */
    public Builder setAceptados(int value) {

      aceptados_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int32 aceptados = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearAceptados() {
      bitField0_ = (bitField0_ & ~0x00000001);
      aceptados_ = 0;
      onChanged();
      return this;
    }

    private int rechazados_ ;
    /**
     * <code>int32 rechazados = 2;</code>
     * @return The rechazados.
     */
    @java.lang.Override
    public int getRechazados() {
      return rechazados_;
    }
    /**
     * <code>int32 rechazados = 2;</code>
     * @param value The rechazados to set.
     * @return This builder for chaining.
     */
    public Builder setRechazados(int value) {

      rechazados_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int32 rechazados = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearRechazados() {
      bitField0_ = (bitField0_ & ~0x00000002);
      rechazados_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object mensaje_ = "";
    /**
     * <code>string mensaje = 3;</code>
     * @return The mensaje.
     */
    public java.lang.String getMensaje() {
      java.lang.Object ref = mensaje_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mensaje_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string mensaje = 3;</code>
     * @return The bytes for mensaje.
     */
    public com.google.protobuf.ByteString
        getMensajeBytes() {
      java.lang.Object ref = mensaje_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mensaje_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string mensaje = 3;</code>
     * @param value The mensaje to set.
     * @return This builder for chaining.
     */
    public Builder setMensaje(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      mensaje_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string mensaje = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearMensaje() {
      mensaje_ = getDefaultInstance().getMensaje();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string mensaje = 3;</code>
     * @param value The bytes for mensaje to set.
     * @return This builder for chaining.
     */
    public Builder setMensajeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      mensaje_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:nodoprocesamiento.RespuestaRecepcionTrabajos)
  }

  // @@protoc_insertion_point(class_scope:nodoprocesamiento.RespuestaRecepcionTrabajos)
  private static final co.edu.upb.grpc.RespuestaRecepcionTrabajos DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new co.edu.upb.grpc.RespuestaRecepcionTrabajos();
  }

  public static co.edu.upb.grpc.RespuestaRecepcionTrabajos getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RespuestaRecepcionTrabajos>
      PARSER = new com.google.protobuf.AbstractParser<RespuestaRecepcionTrabajos>() {
    @java.lang.Override
    public RespuestaRecepcionTrabajos parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<RespuestaRecepcionTrabajos> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RespuestaRecepcionTrabajos> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public co.edu.upb.grpc.RespuestaRecepcionTrabajos getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

