// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nodo_procesamiento.proto

// Protobuf Java Version: 3.25.3
package co.edu.upb.grpc;

public interface SolicitudTrabajosRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:nodoprocesamiento.SolicitudTrabajosRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .nodoprocesamiento.TrabajoImagenRequest trabajos = 1;</code>
   */
  java.util.List<co.edu.upb.grpc.TrabajoImagenRequest> 
      getTrabajosList();
  /**
   * <code>repeated .nodoprocesamiento.TrabajoImagenRequest trabajos = 1;</code>
   */
  co.edu.upb.grpc.TrabajoImagenRequest getTrabajos(int index);
  /**
   * <code>repeated .nodoprocesamiento.TrabajoImagenRequest trabajos = 1;</code>
   */
  int getTrabajosCount();
  /**
   * <code>repeated .nodoprocesamiento.TrabajoImagenRequest trabajos = 1;</code>
   */
  java.util.List<? extends co.edu.upb.grpc.TrabajoImagenRequestOrBuilder> 
      getTrabajosOrBuilderList();
  /**
   * <code>repeated .nodoprocesamiento.TrabajoImagenRequest trabajos = 1;</code>
   */
  co.edu.upb.grpc.TrabajoImagenRequestOrBuilder getTrabajosOrBuilder(
      int index);
}
