// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nodo_procesamiento.proto

// Protobuf Java Version: 3.25.3
package co.edu.upb.grpc;

/**
 * Protobuf type {@code nodoprocesamiento.SolicitudTrabajosRequest}
 */
public final class SolicitudTrabajosRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:nodoprocesamiento.SolicitudTrabajosRequest)
    SolicitudTrabajosRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SolicitudTrabajosRequest.newBuilder() to construct.
  private SolicitudTrabajosRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SolicitudTrabajosRequest() {
    trabajos_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SolicitudTrabajosRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return co.edu.upb.grpc.NodoProcesamientoProto.internal_static_nodoprocesamiento_SolicitudTrabajosRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return co.edu.upb.grpc.NodoProcesamientoProto.internal_static_nodoprocesamiento_SolicitudTrabajosRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            co.edu.upb.grpc.SolicitudTrabajosRequest.class, co.edu.upb.grpc.SolicitudTrabajosRequest.Builder.class);
  }

  public static final int TRABAJOS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<co.edu.upb.grpc.TrabajoImagenRequest> trabajos_;
  /**
   * <code>repeated .nodoprocesamiento.TrabajoImagenRequest trabajos = 1;</code>
   */
  @java.lang.Override
  public java.util.List<co.edu.upb.grpc.TrabajoImagenRequest> getTrabajosList() {
    return trabajos_;
  }
  /**
   * <code>repeated .nodoprocesamiento.TrabajoImagenRequest trabajos = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends co.edu.upb.grpc.TrabajoImagenRequestOrBuilder> 
      getTrabajosOrBuilderList() {
    return trabajos_;
  }
  /**
   * <code>repeated .nodoprocesamiento.TrabajoImagenRequest trabajos = 1;</code>
   */
  @java.lang.Override
  public int getTrabajosCount() {
    return trabajos_.size();
  }
  /**
   * <code>repeated .nodoprocesamiento.TrabajoImagenRequest trabajos = 1;</code>
   */
  @java.lang.Override
  public co.edu.upb.grpc.TrabajoImagenRequest getTrabajos(int index) {
    return trabajos_.get(index);
  }
  /**
   * <code>repeated .nodoprocesamiento.TrabajoImagenRequest trabajos = 1;</code>
   */
  @java.lang.Override
  public co.edu.upb.grpc.TrabajoImagenRequestOrBuilder getTrabajosOrBuilder(
      int index) {
    return trabajos_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < trabajos_.size(); i++) {
      output.writeMessage(1, trabajos_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < trabajos_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, trabajos_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof co.edu.upb.grpc.SolicitudTrabajosRequest)) {
      return super.equals(obj);
    }
    co.edu.upb.grpc.SolicitudTrabajosRequest other = (co.edu.upb.grpc.SolicitudTrabajosRequest) obj;

    if (!getTrabajosList()
        .equals(other.getTrabajosList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getTrabajosCount() > 0) {
      hash = (37 * hash) + TRABAJOS_FIELD_NUMBER;
      hash = (53 * hash) + getTrabajosList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static co.edu.upb.grpc.SolicitudTrabajosRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static co.edu.upb.grpc.SolicitudTrabajosRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static co.edu.upb.grpc.SolicitudTrabajosRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static co.edu.upb.grpc.SolicitudTrabajosRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static co.edu.upb.grpc.SolicitudTrabajosRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static co.edu.upb.grpc.SolicitudTrabajosRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static co.edu.upb.grpc.SolicitudTrabajosRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static co.edu.upb.grpc.SolicitudTrabajosRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static co.edu.upb.grpc.SolicitudTrabajosRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static co.edu.upb.grpc.SolicitudTrabajosRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static co.edu.upb.grpc.SolicitudTrabajosRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static co.edu.upb.grpc.SolicitudTrabajosRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(co.edu.upb.grpc.SolicitudTrabajosRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code nodoprocesamiento.SolicitudTrabajosRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:nodoprocesamiento.SolicitudTrabajosRequest)
      co.edu.upb.grpc.SolicitudTrabajosRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return co.edu.upb.grpc.NodoProcesamientoProto.internal_static_nodoprocesamiento_SolicitudTrabajosRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return co.edu.upb.grpc.NodoProcesamientoProto.internal_static_nodoprocesamiento_SolicitudTrabajosRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              co.edu.upb.grpc.SolicitudTrabajosRequest.class, co.edu.upb.grpc.SolicitudTrabajosRequest.Builder.class);
    }

    // Construct using co.edu.upb.grpc.SolicitudTrabajosRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (trabajosBuilder_ == null) {
        trabajos_ = java.util.Collections.emptyList();
      } else {
        trabajos_ = null;
        trabajosBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return co.edu.upb.grpc.NodoProcesamientoProto.internal_static_nodoprocesamiento_SolicitudTrabajosRequest_descriptor;
    }

    @java.lang.Override
    public co.edu.upb.grpc.SolicitudTrabajosRequest getDefaultInstanceForType() {
      return co.edu.upb.grpc.SolicitudTrabajosRequest.getDefaultInstance();
    }

    @java.lang.Override
    public co.edu.upb.grpc.SolicitudTrabajosRequest build() {
      co.edu.upb.grpc.SolicitudTrabajosRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public co.edu.upb.grpc.SolicitudTrabajosRequest buildPartial() {
      co.edu.upb.grpc.SolicitudTrabajosRequest result = new co.edu.upb.grpc.SolicitudTrabajosRequest(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(co.edu.upb.grpc.SolicitudTrabajosRequest result) {
      if (trabajosBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          trabajos_ = java.util.Collections.unmodifiableList(trabajos_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.trabajos_ = trabajos_;
      } else {
        result.trabajos_ = trabajosBuilder_.build();
      }
    }

    private void buildPartial0(co.edu.upb.grpc.SolicitudTrabajosRequest result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof co.edu.upb.grpc.SolicitudTrabajosRequest) {
        return mergeFrom((co.edu.upb.grpc.SolicitudTrabajosRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(co.edu.upb.grpc.SolicitudTrabajosRequest other) {
      if (other == co.edu.upb.grpc.SolicitudTrabajosRequest.getDefaultInstance()) return this;
      if (trabajosBuilder_ == null) {
        if (!other.trabajos_.isEmpty()) {
          if (trabajos_.isEmpty()) {
            trabajos_ = other.trabajos_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureTrabajosIsMutable();
            trabajos_.addAll(other.trabajos_);
          }
          onChanged();
        }
      } else {
        if (!other.trabajos_.isEmpty()) {
          if (trabajosBuilder_.isEmpty()) {
            trabajosBuilder_.dispose();
            trabajosBuilder_ = null;
            trabajos_ = other.trabajos_;
            bitField0_ = (bitField0_ & ~0x00000001);
            trabajosBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getTrabajosFieldBuilder() : null;
          } else {
            trabajosBuilder_.addAllMessages(other.trabajos_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              co.edu.upb.grpc.TrabajoImagenRequest m =
                  input.readMessage(
                      co.edu.upb.grpc.TrabajoImagenRequest.parser(),
                      extensionRegistry);
              if (trabajosBuilder_ == null) {
                ensureTrabajosIsMutable();
                trabajos_.add(m);
              } else {
                trabajosBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<co.edu.upb.grpc.TrabajoImagenRequest> trabajos_ =
      java.util.Collections.emptyList();
    private void ensureTrabajosIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        trabajos_ = new java.util.ArrayList<co.edu.upb.grpc.TrabajoImagenRequest>(trabajos_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        co.edu.upb.grpc.TrabajoImagenRequest, co.edu.upb.grpc.TrabajoImagenRequest.Builder, co.edu.upb.grpc.TrabajoImagenRequestOrBuilder> trabajosBuilder_;

    /**
     * <code>repeated .nodoprocesamiento.TrabajoImagenRequest trabajos = 1;</code>
     */
    public java.util.List<co.edu.upb.grpc.TrabajoImagenRequest> getTrabajosList() {
      if (trabajosBuilder_ == null) {
        return java.util.Collections.unmodifiableList(trabajos_);
      } else {
        return trabajosBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .nodoprocesamiento.TrabajoImagenRequest trabajos = 1;</code>
     */
    public int getTrabajosCount() {
      if (trabajosBuilder_ == null) {
        return trabajos_.size();
      } else {
        return trabajosBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .nodoprocesamiento.TrabajoImagenRequest trabajos = 1;</code>
     */
    public co.edu.upb.grpc.TrabajoImagenRequest getTrabajos(int index) {
      if (trabajosBuilder_ == null) {
        return trabajos_.get(index);
      } else {
        return trabajosBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .nodoprocesamiento.TrabajoImagenRequest trabajos = 1;</code>
     */
    public Builder setTrabajos(
        int index, co.edu.upb.grpc.TrabajoImagenRequest value) {
      if (trabajosBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTrabajosIsMutable();
        trabajos_.set(index, value);
        onChanged();
      } else {
        trabajosBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .nodoprocesamiento.TrabajoImagenRequest trabajos = 1;</code>
     */
    public Builder setTrabajos(
        int index, co.edu.upb.grpc.TrabajoImagenRequest.Builder builderForValue) {
      if (trabajosBuilder_ == null) {
        ensureTrabajosIsMutable();
        trabajos_.set(index, builderForValue.build());
        onChanged();
      } else {
        trabajosBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .nodoprocesamiento.TrabajoImagenRequest trabajos = 1;</code>
     */
    public Builder addTrabajos(co.edu.upb.grpc.TrabajoImagenRequest value) {
      if (trabajosBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTrabajosIsMutable();
        trabajos_.add(value);
        onChanged();
      } else {
        trabajosBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .nodoprocesamiento.TrabajoImagenRequest trabajos = 1;</code>
     */
    public Builder addTrabajos(
        int index, co.edu.upb.grpc.TrabajoImagenRequest value) {
      if (trabajosBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTrabajosIsMutable();
        trabajos_.add(index, value);
        onChanged();
      } else {
        trabajosBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .nodoprocesamiento.TrabajoImagenRequest trabajos = 1;</code>
     */
    public Builder addTrabajos(
        co.edu.upb.grpc.TrabajoImagenRequest.Builder builderForValue) {
      if (trabajosBuilder_ == null) {
        ensureTrabajosIsMutable();
        trabajos_.add(builderForValue.build());
        onChanged();
      } else {
        trabajosBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .nodoprocesamiento.TrabajoImagenRequest trabajos = 1;</code>
     */
    public Builder addTrabajos(
        int index, co.edu.upb.grpc.TrabajoImagenRequest.Builder builderForValue) {
      if (trabajosBuilder_ == null) {
        ensureTrabajosIsMutable();
        trabajos_.add(index, builderForValue.build());
        onChanged();
      } else {
        trabajosBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .nodoprocesamiento.TrabajoImagenRequest trabajos = 1;</code>
     */
    public Builder addAllTrabajos(
        java.lang.Iterable<? extends co.edu.upb.grpc.TrabajoImagenRequest> values) {
      if (trabajosBuilder_ == null) {
        ensureTrabajosIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, trabajos_);
        onChanged();
      } else {
        trabajosBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .nodoprocesamiento.TrabajoImagenRequest trabajos = 1;</code>
     */
    public Builder clearTrabajos() {
      if (trabajosBuilder_ == null) {
        trabajos_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        trabajosBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .nodoprocesamiento.TrabajoImagenRequest trabajos = 1;</code>
     */
    public Builder removeTrabajos(int index) {
      if (trabajosBuilder_ == null) {
        ensureTrabajosIsMutable();
        trabajos_.remove(index);
        onChanged();
      } else {
        trabajosBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .nodoprocesamiento.TrabajoImagenRequest trabajos = 1;</code>
     */
    public co.edu.upb.grpc.TrabajoImagenRequest.Builder getTrabajosBuilder(
        int index) {
      return getTrabajosFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .nodoprocesamiento.TrabajoImagenRequest trabajos = 1;</code>
     */
    public co.edu.upb.grpc.TrabajoImagenRequestOrBuilder getTrabajosOrBuilder(
        int index) {
      if (trabajosBuilder_ == null) {
        return trabajos_.get(index);  } else {
        return trabajosBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .nodoprocesamiento.TrabajoImagenRequest trabajos = 1;</code>
     */
    public java.util.List<? extends co.edu.upb.grpc.TrabajoImagenRequestOrBuilder> 
         getTrabajosOrBuilderList() {
      if (trabajosBuilder_ != null) {
        return trabajosBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(trabajos_);
      }
    }
    /**
     * <code>repeated .nodoprocesamiento.TrabajoImagenRequest trabajos = 1;</code>
     */
    public co.edu.upb.grpc.TrabajoImagenRequest.Builder addTrabajosBuilder() {
      return getTrabajosFieldBuilder().addBuilder(
          co.edu.upb.grpc.TrabajoImagenRequest.getDefaultInstance());
    }
    /**
     * <code>repeated .nodoprocesamiento.TrabajoImagenRequest trabajos = 1;</code>
     */
    public co.edu.upb.grpc.TrabajoImagenRequest.Builder addTrabajosBuilder(
        int index) {
      return getTrabajosFieldBuilder().addBuilder(
          index, co.edu.upb.grpc.TrabajoImagenRequest.getDefaultInstance());
    }
    /**
     * <code>repeated .nodoprocesamiento.TrabajoImagenRequest trabajos = 1;</code>
     */
    public java.util.List<co.edu.upb.grpc.TrabajoImagenRequest.Builder> 
         getTrabajosBuilderList() {
      return getTrabajosFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        co.edu.upb.grpc.TrabajoImagenRequest, co.edu.upb.grpc.TrabajoImagenRequest.Builder, co.edu.upb.grpc.TrabajoImagenRequestOrBuilder> 
        getTrabajosFieldBuilder() {
      if (trabajosBuilder_ == null) {
        trabajosBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            co.edu.upb.grpc.TrabajoImagenRequest, co.edu.upb.grpc.TrabajoImagenRequest.Builder, co.edu.upb.grpc.TrabajoImagenRequestOrBuilder>(
                trabajos_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        trabajos_ = null;
      }
      return trabajosBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:nodoprocesamiento.SolicitudTrabajosRequest)
  }

  // @@protoc_insertion_point(class_scope:nodoprocesamiento.SolicitudTrabajosRequest)
  private static final co.edu.upb.grpc.SolicitudTrabajosRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new co.edu.upb.grpc.SolicitudTrabajosRequest();
  }

  public static co.edu.upb.grpc.SolicitudTrabajosRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SolicitudTrabajosRequest>
      PARSER = new com.google.protobuf.AbstractParser<SolicitudTrabajosRequest>() {
    @java.lang.Override
    public SolicitudTrabajosRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SolicitudTrabajosRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SolicitudTrabajosRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public co.edu.upb.grpc.SolicitudTrabajosRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

