// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nodo_procesamiento.proto

// Protobuf Java Version: 3.25.3
package co.edu.upb.grpc;

public interface TrabajoImagenRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:nodoprocesamiento.TrabajoImagenRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 idLote = 1;</code>
   * @return The idLote.
   */
  long getIdLote();

  /**
   * <code>int64 idImagen = 2;</code>
   * @return The idImagen.
   */
  long getIdImagen();

  /**
   * <code>string nombreArchivo = 3;</code>
   * @return The nombreArchivo.
   */
  java.lang.String getNombreArchivo();
  /**
   * <code>string nombreArchivo = 3;</code>
   * @return The bytes for nombreArchivo.
   */
  com.google.protobuf.ByteString
      getNombreArchivoBytes();

  /**
   * <code>string rutaOrigen = 4;</code>
   * @return The rutaOrigen.
   */
  java.lang.String getRutaOrigen();
  /**
   * <code>string rutaOrigen = 4;</code>
   * @return The bytes for rutaOrigen.
   */
  com.google.protobuf.ByteString
      getRutaOrigenBytes();

  /**
   * <code>repeated .nodoprocesamiento.TransformacionRequest transformaciones = 5;</code>
   */
  java.util.List<co.edu.upb.grpc.TransformacionRequest> 
      getTransformacionesList();
  /**
   * <code>repeated .nodoprocesamiento.TransformacionRequest transformaciones = 5;</code>
   */
  co.edu.upb.grpc.TransformacionRequest getTransformaciones(int index);
  /**
   * <code>repeated .nodoprocesamiento.TransformacionRequest transformaciones = 5;</code>
   */
  int getTransformacionesCount();
  /**
   * <code>repeated .nodoprocesamiento.TransformacionRequest transformaciones = 5;</code>
   */
  java.util.List<? extends co.edu.upb.grpc.TransformacionRequestOrBuilder> 
      getTransformacionesOrBuilderList();
  /**
   * <code>repeated .nodoprocesamiento.TransformacionRequest transformaciones = 5;</code>
   */
  co.edu.upb.grpc.TransformacionRequestOrBuilder getTransformacionesOrBuilder(
      int index);
}
