// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nodo_procesamiento.proto

// Protobuf Java Version: 3.25.3
package co.edu.upb.grpc;

/**
 * Protobuf type {@code nodoprocesamiento.TrabajoImagenRequest}
 */
public final class TrabajoImagenRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:nodoprocesamiento.TrabajoImagenRequest)
    TrabajoImagenRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TrabajoImagenRequest.newBuilder() to construct.
  private TrabajoImagenRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TrabajoImagenRequest() {
    nombreArchivo_ = "";
    rutaOrigen_ = "";
    transformaciones_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new TrabajoImagenRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return co.edu.upb.grpc.NodoProcesamientoProto.internal_static_nodoprocesamiento_TrabajoImagenRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return co.edu.upb.grpc.NodoProcesamientoProto.internal_static_nodoprocesamiento_TrabajoImagenRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            co.edu.upb.grpc.TrabajoImagenRequest.class, co.edu.upb.grpc.TrabajoImagenRequest.Builder.class);
  }

  public static final int IDLOTE_FIELD_NUMBER = 1;
  private long idLote_ = 0L;
  /**
   * <code>int64 idLote = 1;</code>
   * @return The idLote.
   */
  @java.lang.Override
  public long getIdLote() {
    return idLote_;
  }

  public static final int IDIMAGEN_FIELD_NUMBER = 2;
  private long idImagen_ = 0L;
  /**
   * <code>int64 idImagen = 2;</code>
   * @return The idImagen.
   */
  @java.lang.Override
  public long getIdImagen() {
    return idImagen_;
  }

  public static final int NOMBREARCHIVO_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object nombreArchivo_ = "";
  /**
   * <code>string nombreArchivo = 3;</code>
   * @return The nombreArchivo.
   */
  @java.lang.Override
  public java.lang.String getNombreArchivo() {
    java.lang.Object ref = nombreArchivo_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      nombreArchivo_ = s;
      return s;
    }
  }
  /**
   * <code>string nombreArchivo = 3;</code>
   * @return The bytes for nombreArchivo.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNombreArchivoBytes() {
    java.lang.Object ref = nombreArchivo_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      nombreArchivo_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RUTAORIGEN_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object rutaOrigen_ = "";
  /**
   * <code>string rutaOrigen = 4;</code>
   * @return The rutaOrigen.
   */
  @java.lang.Override
  public java.lang.String getRutaOrigen() {
    java.lang.Object ref = rutaOrigen_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      rutaOrigen_ = s;
      return s;
    }
  }
  /**
   * <code>string rutaOrigen = 4;</code>
   * @return The bytes for rutaOrigen.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRutaOrigenBytes() {
    java.lang.Object ref = rutaOrigen_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      rutaOrigen_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TRANSFORMACIONES_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private java.util.List<co.edu.upb.grpc.TransformacionRequest> transformaciones_;
  /**
   * <code>repeated .nodoprocesamiento.TransformacionRequest transformaciones = 5;</code>
   */
  @java.lang.Override
  public java.util.List<co.edu.upb.grpc.TransformacionRequest> getTransformacionesList() {
    return transformaciones_;
  }
  /**
   * <code>repeated .nodoprocesamiento.TransformacionRequest transformaciones = 5;</code>
   */
  @java.lang.Override
  public java.util.List<? extends co.edu.upb.grpc.TransformacionRequestOrBuilder> 
      getTransformacionesOrBuilderList() {
    return transformaciones_;
  }
  /**
   * <code>repeated .nodoprocesamiento.TransformacionRequest transformaciones = 5;</code>
   */
  @java.lang.Override
  public int getTransformacionesCount() {
    return transformaciones_.size();
  }
  /**
   * <code>repeated .nodoprocesamiento.TransformacionRequest transformaciones = 5;</code>
   */
  @java.lang.Override
  public co.edu.upb.grpc.TransformacionRequest getTransformaciones(int index) {
    return transformaciones_.get(index);
  }
  /**
   * <code>repeated .nodoprocesamiento.TransformacionRequest transformaciones = 5;</code>
   */
  @java.lang.Override
  public co.edu.upb.grpc.TransformacionRequestOrBuilder getTransformacionesOrBuilder(
      int index) {
    return transformaciones_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (idLote_ != 0L) {
      output.writeInt64(1, idLote_);
    }
    if (idImagen_ != 0L) {
      output.writeInt64(2, idImagen_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(nombreArchivo_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, nombreArchivo_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(rutaOrigen_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, rutaOrigen_);
    }
    for (int i = 0; i < transformaciones_.size(); i++) {
      output.writeMessage(5, transformaciones_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (idLote_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, idLote_);
    }
    if (idImagen_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, idImagen_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(nombreArchivo_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, nombreArchivo_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(rutaOrigen_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, rutaOrigen_);
    }
    for (int i = 0; i < transformaciones_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, transformaciones_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof co.edu.upb.grpc.TrabajoImagenRequest)) {
      return super.equals(obj);
    }
    co.edu.upb.grpc.TrabajoImagenRequest other = (co.edu.upb.grpc.TrabajoImagenRequest) obj;

    if (getIdLote()
        != other.getIdLote()) return false;
    if (getIdImagen()
        != other.getIdImagen()) return false;
    if (!getNombreArchivo()
        .equals(other.getNombreArchivo())) return false;
    if (!getRutaOrigen()
        .equals(other.getRutaOrigen())) return false;
    if (!getTransformacionesList()
        .equals(other.getTransformacionesList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + IDLOTE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getIdLote());
    hash = (37 * hash) + IDIMAGEN_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getIdImagen());
    hash = (37 * hash) + NOMBREARCHIVO_FIELD_NUMBER;
    hash = (53 * hash) + getNombreArchivo().hashCode();
    hash = (37 * hash) + RUTAORIGEN_FIELD_NUMBER;
    hash = (53 * hash) + getRutaOrigen().hashCode();
    if (getTransformacionesCount() > 0) {
      hash = (37 * hash) + TRANSFORMACIONES_FIELD_NUMBER;
      hash = (53 * hash) + getTransformacionesList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static co.edu.upb.grpc.TrabajoImagenRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static co.edu.upb.grpc.TrabajoImagenRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static co.edu.upb.grpc.TrabajoImagenRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static co.edu.upb.grpc.TrabajoImagenRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static co.edu.upb.grpc.TrabajoImagenRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static co.edu.upb.grpc.TrabajoImagenRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static co.edu.upb.grpc.TrabajoImagenRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static co.edu.upb.grpc.TrabajoImagenRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static co.edu.upb.grpc.TrabajoImagenRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static co.edu.upb.grpc.TrabajoImagenRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static co.edu.upb.grpc.TrabajoImagenRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static co.edu.upb.grpc.TrabajoImagenRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(co.edu.upb.grpc.TrabajoImagenRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code nodoprocesamiento.TrabajoImagenRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:nodoprocesamiento.TrabajoImagenRequest)
      co.edu.upb.grpc.TrabajoImagenRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return co.edu.upb.grpc.NodoProcesamientoProto.internal_static_nodoprocesamiento_TrabajoImagenRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return co.edu.upb.grpc.NodoProcesamientoProto.internal_static_nodoprocesamiento_TrabajoImagenRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              co.edu.upb.grpc.TrabajoImagenRequest.class, co.edu.upb.grpc.TrabajoImagenRequest.Builder.class);
    }

    // Construct using co.edu.upb.grpc.TrabajoImagenRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      idLote_ = 0L;
      idImagen_ = 0L;
      nombreArchivo_ = "";
      rutaOrigen_ = "";
      if (transformacionesBuilder_ == null) {
        transformaciones_ = java.util.Collections.emptyList();
      } else {
        transformaciones_ = null;
        transformacionesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000010);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return co.edu.upb.grpc.NodoProcesamientoProto.internal_static_nodoprocesamiento_TrabajoImagenRequest_descriptor;
    }

    @java.lang.Override
    public co.edu.upb.grpc.TrabajoImagenRequest getDefaultInstanceForType() {
      return co.edu.upb.grpc.TrabajoImagenRequest.getDefaultInstance();
    }

    @java.lang.Override
    public co.edu.upb.grpc.TrabajoImagenRequest build() {
      co.edu.upb.grpc.TrabajoImagenRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public co.edu.upb.grpc.TrabajoImagenRequest buildPartial() {
      co.edu.upb.grpc.TrabajoImagenRequest result = new co.edu.upb.grpc.TrabajoImagenRequest(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(co.edu.upb.grpc.TrabajoImagenRequest result) {
      if (transformacionesBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0)) {
          transformaciones_ = java.util.Collections.unmodifiableList(transformaciones_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.transformaciones_ = transformaciones_;
      } else {
        result.transformaciones_ = transformacionesBuilder_.build();
      }
    }

    private void buildPartial0(co.edu.upb.grpc.TrabajoImagenRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.idLote_ = idLote_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.idImagen_ = idImagen_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.nombreArchivo_ = nombreArchivo_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.rutaOrigen_ = rutaOrigen_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof co.edu.upb.grpc.TrabajoImagenRequest) {
        return mergeFrom((co.edu.upb.grpc.TrabajoImagenRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(co.edu.upb.grpc.TrabajoImagenRequest other) {
      if (other == co.edu.upb.grpc.TrabajoImagenRequest.getDefaultInstance()) return this;
      if (other.getIdLote() != 0L) {
        setIdLote(other.getIdLote());
      }
      if (other.getIdImagen() != 0L) {
        setIdImagen(other.getIdImagen());
      }
      if (!other.getNombreArchivo().isEmpty()) {
        nombreArchivo_ = other.nombreArchivo_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getRutaOrigen().isEmpty()) {
        rutaOrigen_ = other.rutaOrigen_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (transformacionesBuilder_ == null) {
        if (!other.transformaciones_.isEmpty()) {
          if (transformaciones_.isEmpty()) {
            transformaciones_ = other.transformaciones_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureTransformacionesIsMutable();
            transformaciones_.addAll(other.transformaciones_);
          }
          onChanged();
        }
      } else {
        if (!other.transformaciones_.isEmpty()) {
          if (transformacionesBuilder_.isEmpty()) {
            transformacionesBuilder_.dispose();
            transformacionesBuilder_ = null;
            transformaciones_ = other.transformaciones_;
            bitField0_ = (bitField0_ & ~0x00000010);
            transformacionesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getTransformacionesFieldBuilder() : null;
          } else {
            transformacionesBuilder_.addAllMessages(other.transformaciones_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              idLote_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              idImagen_ = input.readInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              nombreArchivo_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              rutaOrigen_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              co.edu.upb.grpc.TransformacionRequest m =
                  input.readMessage(
                      co.edu.upb.grpc.TransformacionRequest.parser(),
                      extensionRegistry);
              if (transformacionesBuilder_ == null) {
                ensureTransformacionesIsMutable();
                transformaciones_.add(m);
              } else {
                transformacionesBuilder_.addMessage(m);
              }
              break;
            } // case 42
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long idLote_ ;
    /**
     * <code>int64 idLote = 1;</code>
     * @return The idLote.
     */
    @java.lang.Override
    public long getIdLote() {
      return idLote_;
    }
    /**
     * <code>int64 idLote = 1;</code>
     * @param value The idLote to set.
     * @return This builder for chaining.
     */
    public Builder setIdLote(long value) {

      idLote_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int64 idLote = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearIdLote() {
      bitField0_ = (bitField0_ & ~0x00000001);
      idLote_ = 0L;
      onChanged();
      return this;
    }

    private long idImagen_ ;
    /**
     * <code>int64 idImagen = 2;</code>
     * @return The idImagen.
     */
    @java.lang.Override
    public long getIdImagen() {
      return idImagen_;
    }
    /**
     * <code>int64 idImagen = 2;</code>
     * @param value The idImagen to set.
     * @return This builder for chaining.
     */
    public Builder setIdImagen(long value) {

      idImagen_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int64 idImagen = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearIdImagen() {
      bitField0_ = (bitField0_ & ~0x00000002);
      idImagen_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object nombreArchivo_ = "";
    /**
     * <code>string nombreArchivo = 3;</code>
     * @return The nombreArchivo.
     */
    public java.lang.String getNombreArchivo() {
      java.lang.Object ref = nombreArchivo_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nombreArchivo_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string nombreArchivo = 3;</code>
     * @return The bytes for nombreArchivo.
     */
    public com.google.protobuf.ByteString
        getNombreArchivoBytes() {
      java.lang.Object ref = nombreArchivo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nombreArchivo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string nombreArchivo = 3;</code>
     * @param value The nombreArchivo to set.
     * @return This builder for chaining.
     */
    public Builder setNombreArchivo(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      nombreArchivo_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string nombreArchivo = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearNombreArchivo() {
      nombreArchivo_ = getDefaultInstance().getNombreArchivo();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string nombreArchivo = 3;</code>
     * @param value The bytes for nombreArchivo to set.
     * @return This builder for chaining.
     */
    public Builder setNombreArchivoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      nombreArchivo_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object rutaOrigen_ = "";
    /**
     * <code>string rutaOrigen = 4;</code>
     * @return The rutaOrigen.
     */
    public java.lang.String getRutaOrigen() {
      java.lang.Object ref = rutaOrigen_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        rutaOrigen_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string rutaOrigen = 4;</code>
     * @return The bytes for rutaOrigen.
     */
    public com.google.protobuf.ByteString
        getRutaOrigenBytes() {
      java.lang.Object ref = rutaOrigen_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        rutaOrigen_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string rutaOrigen = 4;</code>
     * @param value The rutaOrigen to set.
     * @return This builder for chaining.
     */
    public Builder setRutaOrigen(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      rutaOrigen_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string rutaOrigen = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearRutaOrigen() {
      rutaOrigen_ = getDefaultInstance().getRutaOrigen();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string rutaOrigen = 4;</code>
     * @param value The bytes for rutaOrigen to set.
     * @return This builder for chaining.
     */
    public Builder setRutaOrigenBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      rutaOrigen_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.util.List<co.edu.upb.grpc.TransformacionRequest> transformaciones_ =
      java.util.Collections.emptyList();
    private void ensureTransformacionesIsMutable() {
      if (!((bitField0_ & 0x00000010) != 0)) {
        transformaciones_ = new java.util.ArrayList<co.edu.upb.grpc.TransformacionRequest>(transformaciones_);
        bitField0_ |= 0x00000010;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        co.edu.upb.grpc.TransformacionRequest, co.edu.upb.grpc.TransformacionRequest.Builder, co.edu.upb.grpc.TransformacionRequestOrBuilder> transformacionesBuilder_;

    /**
     * <code>repeated .nodoprocesamiento.TransformacionRequest transformaciones = 5;</code>
     */
    public java.util.List<co.edu.upb.grpc.TransformacionRequest> getTransformacionesList() {
      if (transformacionesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(transformaciones_);
      } else {
        return transformacionesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .nodoprocesamiento.TransformacionRequest transformaciones = 5;</code>
     */
    public int getTransformacionesCount() {
      if (transformacionesBuilder_ == null) {
        return transformaciones_.size();
      } else {
        return transformacionesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .nodoprocesamiento.TransformacionRequest transformaciones = 5;</code>
     */
    public co.edu.upb.grpc.TransformacionRequest getTransformaciones(int index) {
      if (transformacionesBuilder_ == null) {
        return transformaciones_.get(index);
      } else {
        return transformacionesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .nodoprocesamiento.TransformacionRequest transformaciones = 5;</code>
     */
    public Builder setTransformaciones(
        int index, co.edu.upb.grpc.TransformacionRequest value) {
      if (transformacionesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTransformacionesIsMutable();
        transformaciones_.set(index, value);
        onChanged();
      } else {
        transformacionesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .nodoprocesamiento.TransformacionRequest transformaciones = 5;</code>
     */
    public Builder setTransformaciones(
        int index, co.edu.upb.grpc.TransformacionRequest.Builder builderForValue) {
      if (transformacionesBuilder_ == null) {
        ensureTransformacionesIsMutable();
        transformaciones_.set(index, builderForValue.build());
        onChanged();
      } else {
        transformacionesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .nodoprocesamiento.TransformacionRequest transformaciones = 5;</code>
     */
    public Builder addTransformaciones(co.edu.upb.grpc.TransformacionRequest value) {
      if (transformacionesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTransformacionesIsMutable();
        transformaciones_.add(value);
        onChanged();
      } else {
        transformacionesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .nodoprocesamiento.TransformacionRequest transformaciones = 5;</code>
     */
    public Builder addTransformaciones(
        int index, co.edu.upb.grpc.TransformacionRequest value) {
      if (transformacionesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTransformacionesIsMutable();
        transformaciones_.add(index, value);
        onChanged();
      } else {
        transformacionesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .nodoprocesamiento.TransformacionRequest transformaciones = 5;</code>
     */
    public Builder addTransformaciones(
        co.edu.upb.grpc.TransformacionRequest.Builder builderForValue) {
      if (transformacionesBuilder_ == null) {
        ensureTransformacionesIsMutable();
        transformaciones_.add(builderForValue.build());
        onChanged();
      } else {
        transformacionesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .nodoprocesamiento.TransformacionRequest transformaciones = 5;</code>
     */
    public Builder addTransformaciones(
        int index, co.edu.upb.grpc.TransformacionRequest.Builder builderForValue) {
      if (transformacionesBuilder_ == null) {
        ensureTransformacionesIsMutable();
        transformaciones_.add(index, builderForValue.build());
        onChanged();
      } else {
        transformacionesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .nodoprocesamiento.TransformacionRequest transformaciones = 5;</code>
     */
    public Builder addAllTransformaciones(
        java.lang.Iterable<? extends co.edu.upb.grpc.TransformacionRequest> values) {
      if (transformacionesBuilder_ == null) {
        ensureTransformacionesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, transformaciones_);
        onChanged();
      } else {
        transformacionesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .nodoprocesamiento.TransformacionRequest transformaciones = 5;</code>
     */
    public Builder clearTransformaciones() {
      if (transformacionesBuilder_ == null) {
        transformaciones_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
      } else {
        transformacionesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .nodoprocesamiento.TransformacionRequest transformaciones = 5;</code>
     */
    public Builder removeTransformaciones(int index) {
      if (transformacionesBuilder_ == null) {
        ensureTransformacionesIsMutable();
        transformaciones_.remove(index);
        onChanged();
      } else {
        transformacionesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .nodoprocesamiento.TransformacionRequest transformaciones = 5;</code>
     */
    public co.edu.upb.grpc.TransformacionRequest.Builder getTransformacionesBuilder(
        int index) {
      return getTransformacionesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .nodoprocesamiento.TransformacionRequest transformaciones = 5;</code>
     */
    public co.edu.upb.grpc.TransformacionRequestOrBuilder getTransformacionesOrBuilder(
        int index) {
      if (transformacionesBuilder_ == null) {
        return transformaciones_.get(index);  } else {
        return transformacionesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .nodoprocesamiento.TransformacionRequest transformaciones = 5;</code>
     */
    public java.util.List<? extends co.edu.upb.grpc.TransformacionRequestOrBuilder> 
         getTransformacionesOrBuilderList() {
      if (transformacionesBuilder_ != null) {
        return transformacionesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(transformaciones_);
      }
    }
    /**
     * <code>repeated .nodoprocesamiento.TransformacionRequest transformaciones = 5;</code>
     */
    public co.edu.upb.grpc.TransformacionRequest.Builder addTransformacionesBuilder() {
      return getTransformacionesFieldBuilder().addBuilder(
          co.edu.upb.grpc.TransformacionRequest.getDefaultInstance());
    }
    /**
     * <code>repeated .nodoprocesamiento.TransformacionRequest transformaciones = 5;</code>
     */
    public co.edu.upb.grpc.TransformacionRequest.Builder addTransformacionesBuilder(
        int index) {
      return getTransformacionesFieldBuilder().addBuilder(
          index, co.edu.upb.grpc.TransformacionRequest.getDefaultInstance());
    }
    /**
     * <code>repeated .nodoprocesamiento.TransformacionRequest transformaciones = 5;</code>
     */
    public java.util.List<co.edu.upb.grpc.TransformacionRequest.Builder> 
         getTransformacionesBuilderList() {
      return getTransformacionesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        co.edu.upb.grpc.TransformacionRequest, co.edu.upb.grpc.TransformacionRequest.Builder, co.edu.upb.grpc.TransformacionRequestOrBuilder> 
        getTransformacionesFieldBuilder() {
      if (transformacionesBuilder_ == null) {
        transformacionesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            co.edu.upb.grpc.TransformacionRequest, co.edu.upb.grpc.TransformacionRequest.Builder, co.edu.upb.grpc.TransformacionRequestOrBuilder>(
                transformaciones_,
                ((bitField0_ & 0x00000010) != 0),
                getParentForChildren(),
                isClean());
        transformaciones_ = null;
      }
      return transformacionesBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:nodoprocesamiento.TrabajoImagenRequest)
  }

  // @@protoc_insertion_point(class_scope:nodoprocesamiento.TrabajoImagenRequest)
  private static final co.edu.upb.grpc.TrabajoImagenRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new co.edu.upb.grpc.TrabajoImagenRequest();
  }

  public static co.edu.upb.grpc.TrabajoImagenRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TrabajoImagenRequest>
      PARSER = new com.google.protobuf.AbstractParser<TrabajoImagenRequest>() {
    @java.lang.Override
    public TrabajoImagenRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<TrabajoImagenRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TrabajoImagenRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public co.edu.upb.grpc.TrabajoImagenRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

